### PR TITLE
Gitpod configuration updated

### PR DESCRIPTION
**Pull request by littleironical**
## Description
Earlier Gitpod used to open the UI version of Keploy. Updated it to the CLI version.

## Type of change
- [x] New feature (non-breaking change which adds functionality).

## Checklist:
- [ ] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Sarthak160** [comment]
- Hi @littleironical , We can update keploy server version to the latest `go.keploy.io/server v0.7.13 // indirect` and sdk version to `github.com/keploy/go-sdk v0.7.4` . Latest has changes for SQL spec which allows user to generate sql mocks in a more readable format . 
- We can add folder naming sample-tests (add a comment in yaml that these tests are generated by keploy) which will basically give an idea that how mocks and tests looks like after a successfull record session .

**Comment by littleironical** [comment]
> Hi @littleironical , We can update keploy server version to the latest go.keploy.io/server v0.7.13 // indirect and sdk version to github.com/keploy/go-sdk v0.7.4 . Latest changes has changes for SQL spec which allows user to generate sql mocks in a more readable format .

Where should I do the edit?
I don't think it would be in the `.gitpod.yml` file

Also, I didn't quite understand the 2nd point, can you explain a little more on your perspective?

**Comment by Sarthak160** [comment]
> > Hi @littleironical , We can update keploy server version to the latest go.keploy.io/server v0.7.13 // indirect and sdk version to github.com/keploy/go-sdk v0.7.4 . Latest changes has changes for SQL spec which allows user to generate sql mocks in a more readable format .
> 
> Where should I do the edit? I don't think it would be in the `.gitpod.yml` file
> 
> Also, I didn't quite understand the 2nd point, can you explain a little more on your perspective?

1) You have to make changes in go.mod file for that.
2) For the second one, you have to create some tests and mocks and rename the folder to sample tests (in the code base itself ) so that the user can take a glimpse that how tests and mocks would look like for this app .

You can do these few changes in this PR itself .

**Comment by littleironical** [comment]
Got it 👍

**Comment by littleironical** [comment]
@Sarthak160 Did the 2 requested changes, kindly check.
I've created a folder names `Files-Generated-By-Keploy` in which I've added the mocks, tests, and the test reports together within the `echo-sql` application.

**Comment by Sarthak160** [comment]
> @Sarthak160 Did the 2 requested changes, kindly check. I've created a folder names `Files-Generated-By-Keploy` in which I've added the mocks, tests, and the test reports together within the `echo-sql` application.

@littleironical I have tried it using gitpod , It works fine 🔥 .  Can you please change the name to `example-keploy-tests` instead of `Files-Generated-By-Keploy` .

**Comment by littleironical** [comment]
Done ✅

**Review by Sarthak160 — APPROVED** [review]
LGTM

**Pull request merged**
