### PR TITLE
feat: add gin-elastic sample app

### PR DESCRIPTION
**Pull request by iamskp99**
This PR is for this issue : https://github.com/keploy/go-sdk/issues/122

- Added a sample elastic-search app to test Keploy integration capabilities.
- Internally, elastic-search uses an HTTP client for making API calls to the database. Therefore, we used keploy's HTTP client integration to wrap.

### CODE REVIEW

**Comment by AnkitKumarvaid** [comment]
@iamskp99 
I was trying to test your PR and followed the readme for that. 
https://github.com/iamskp99/samples-go/tree/add_sample_app_for_elastic/gin-elastic


But I'm getting 500 server error on get request
according to the readme, pointing towards ###2. Get the movie name from elastic-search 



postman image
image

vs code terminal image
image


can you plz guide me regarding this?

**Comment by iamskp99** [comment]
Hi @AnkitKumarvaid , there were some issues in curl requests given in the readme. I have fixed them.

**Comment by AnkitKumarvaid** [comment]
@iamskp99 can you plz update the documentation according to the new version of Keploy. Now, Keploy doesn't require docker.  

plz refer [this ](https://github.com/keploy/keploy)  and update it accordingly and Let me know when you are done with the changes.

**Comment by iamskp99** [comment]
@AnkitKumarvaid I have made the changes. If there is anything missing, please let me know

**Comment by AnkitKumarvaid** [comment]
@nehagup   @iamskp99    
Gin-elastic integration is working properly.
I have tested the code locally on my linux ubuntu

-test cases are getting generated automatically
-data mocs are getting generated automatically
-Readme is correct according to the new version of keploy

**Review by nehagup — APPROVED** [review]

**Pull request merged**
