### PR TITLE
Added an http app to test http parser

### PR DESCRIPTION
**Pull request by jaydee029**
For issue keploy/keploy#1871

### CODE REVIEW

**Comment by Sarthak160** [comment]
@jaydee029 Please create a docker-compose file for non linux users as well . Rest Looks good!!

**Review by Sarthak160 — APPROVED** [review]
LGTM

**Comment by jaydee029** [comment]
Hey @Sarthak160 I have added and tested the docker compose for this.

**Comment by gouravkrosx** [comment]
@jaydee029 This PR is not relevant to the related issue. You need to make a simple HTTP server where it is calling some external HTTPS Apis, you can take [catFact](https://catfact.ninja/fact) or [reqres](https://reqres.in/) apis as reference.

**Comment by jaydee029** [comment]
Hey @gouravkrosx I used pokeapi https://pokeapi.co/docs/v2 
isn't this an external https api?

**Comment by gouravkrosx** [comment]
Okay my bad, This looks correct.

**Comment by gouravkrosx** [comment]
@jaydee029 Were all the test cases passing?

**Comment by jaydee029** [comment]
I tested it locally I wrote about it under the issue itself [here](https://github.com/keploy/keploy/pull/2176#issuecomment-2268202855)

**Comment by gouravkrosx** [comment]
@jaydee029 I am not talking about the test pipeline but the keploy tests and mocks of the application, Did the keploy tests run successfully having all passed status?

**Comment by jaydee029** [comment]
Yes they did, I included them in the PR  as well

**Comment by jaydee029** [comment]
@gouravkrosx I just added a screenshot for the same in the issue itself [here](https://github.com/keploy/keploy/pull/2176#issue-2446345765) .

**Pull request merged**
