### PR TITLE
feat: reduce image size from 1GB to 29MB

### PR DESCRIPTION
**Pull request by narharim**
# Issue
- closes https://github.com/keploy/keploy/issues/1349
---
Reduce the size using [multi-stage](https://docs.docker.com/language/golang/build-images/#multi-stage-builds) feature of docker

Screenshot from 2024-01-16 22-53-22

### CODE REVIEW

**Comment by narharim** [comment]
@slayerjain There you go! Let me know your thoughts.

**Comment by slayerjain** [comment]
@narharim thanks for the PR. Please fix the version of the alpine docker container.

**Comment by narharim** [comment]
Done

**Comment by narharim** [comment]
@slayerjain others samples-go project have similar Dockerfile to make image. shall I proceed and make changes to them as well?

**Comment by slayerjain** [comment]
Thanks. 

Please feel free to raise a separate PR for that :)

**Pull request merged**
