### PR TITLE
Added a New Sample Application - Users-Profile

### PR DESCRIPTION
**Pull request by littleironical**
A sample application that gets, creates, updates, and deletes a user's data in the database (MongoDB for this application).

### CODE REVIEW

**Comment by Sarthak160** [comment]
@littleironical We can also wrap mongo as a dependency with our `kmongo` integration in `users-profile/configs/mongodb_setup.go` . This will help to illustrate dependency mocking feature of Keploy as well .

**Comment by littleironical** [comment]
@Sarthak160 where can I find the `kmongo` documentation?

**Comment by Sarthak160** [comment]
> @Sarthak160 where can I find the `kmongo` documentation?

https://docs.keploy.io/docs/go/supported-frameworks#1-mongodb you can refer it from here .

**Comment by littleironical** [comment]
@Sarthak160 I've integrated kmongo into the application

**Comment by littleironical** [comment]
@Sarthak160 I've wrapped mongo as a dependency with `kmongo`

**Comment by Sarthak160** [comment]
> @Sarthak160 I've wrapped mongo as a dependency with `kmongo`

@littleironical  I have fixed the problem of unable to wrap kmongo here #13 . Rest looks fine I have tested too !

**Comment by littleironical** [comment]
I've merged the updates with my code!
`kmongo` is wrapped perfectly now 🎉

**Comment by nehagup** [comment]
Since it is merged already in other PR, closing this one. :)

**Pull request closed without merging**
